version: "3.9"

services:
  api:
    image: 127.0.0.1:5000/api-docker:latest
#    build: .
    deploy:
      placement:
        constraints: [node.role==worker]
      restart_policy:
        condition: any
  reactive:
    image: 127.0.0.1:5000/reactive-streaming-docker:latest
 #   build: .
    deploy:
      placement:
        constraints: [node.role==worker]
      restart_policy:
        condition: any

  mosquitto:
    image: 127.0.0.1:5000/eclipse-mosquitto-docker:latest
  #  build: .
    ports:
      - "1883:1883"
      - "9001:9001"
    deploy:
      endpoint_mode: vip
      placement:
        constraints: [node.role==worker]
      restart_policy:
        condition: any

  influxdb:
    image: influxdb:2.4.0-alpine
    volumes:
      - /efs/influxdb-lib:/var/lib/influxdb2
    env_file:
      # BE SURE TO CHANGE THIS LINE BEFORE GOING TO PRODUCTION
      - /efs/docker-compose-grafana-influxdb/influx2.env
    ports:
      - 8086:8086
    deploy:
      placement:
        constraints: [node.role==worker]
      restart_policy:
        condition: any

  grafana:
    user: "0"
    image: grafana/grafana-oss:9.1.8
    volumes:
      - /efs/docker-compose-grafana-influxdb/grafana/etc:/etc/grafana:ro
      - /efs/grafana-lib:/var/lib/grafana
      - /efs/grafana-log:/var/log/grafana
    env_file:
      # BE SURE TO CHANGE THIS LINE BEFORE GOING TO PRODUCTION
      - /efs/docker-compose-grafana-influxdb/grafana.env
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    deploy:
      placement:
        constraints: [node.role==worker]
      restart_policy:
        condition: any
