---
# vars file for roles/swarm

aws_profile: default
aws_region: us-east-1
nfs_package: nfs-common # nfs-utils on RHEL/CentOS/Amazon Linux
efs_file_system_id: fs-0e6bb701676c3ab17
efs_mount_dir: /efs
